[project]
name = "ep-gost"
version = "0.1.0"
description = ""
authors = [
    {name = "RapunzelChan",email = "rapuncel.chan24@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "pycryptodome (>=3.23.0,<4.0.0)",
    "gostcrypto (>=1.2.5,<2.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
